apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-metrics
  namespace: jupyterhub
  labels:
    app: jupyterhub
    component: hub
spec:
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
  selector:
    app: jupyterhub
    component: hub
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jupyterhub
  namespace: jupyterhub
  labels:
    app: jupyterhub
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: jupyterhub
      component: hub
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-grafana-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  jupyterhub-dashboard.json: |
    {
      "dashboard": {
        "title": "JupyterHub Monitoring",
        "uid": "jupyterhub-arm64",
        "panels": [
          {
            "title": "Active Users",
            "targets": [{
              "expr": "jupyterhub_active_users"
            }],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "title": "Server Start Time",
            "targets": [{
              "expr": "rate(jupyterhub_server_spawn_duration_seconds_sum[5m])"
            }],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "title": "Memory Usage by Environment",
            "targets": [{
              "expr": "sum by (pod) (container_memory_usage_bytes{namespace=\"jupyterhub\"})"
            }],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "title": "CPU Usage by Environment",
            "targets": [{
              "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"jupyterhub\"}[5m]))"
            }],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          }
        ]
      }
    }