name: jupyter-pentesting
channels:
  - conda-forge
  - defaults
dependencies:
  # Python base
  - python=3.11
  - pip
  - ipykernel
  - ipywidgets
  
  # Web Testing
  - requests
  - beautifulsoup4
  - lxml
  - selenium
  - mechanize
  
  # Networking
  - paramiko
  - netmiko
  - pexpect
  - scapy
  
  # Crypto
  - pycryptodome
  - cryptography
  
  # Data Processing
  - pandas
  - numpy
  - matplotlib
  
  # Database
  - sqlalchemy
  - pymongo
  - redis-py
  
  # Utilities
  - click
  - rich
  - typer
  
  # Pip packages for pentesting
  - pip:
    # Web Application Testing
    - wfuzz
    - sqlmap
    - xsser
    - commix
    
    # Network Testing
    - impacket
    - ldap3
    - pysmb
    - netaddr
    
    # Exploitation
    - pwntools
    - ropper
    - ropgadget
    
    # Password/Hash
    - passlib
    - hashid
    - john
    
    # Recon
    - python-whois
    - dnspython
    - shodan
    - censys
    
    # Wireless
    - pywifi
    - scapy-http
    
    # Reporting
    - python-docx
    - pdfkit
    - jinja2
    
    # API Testing
    - postman-to-openapi
    - openapi-spec-validator