name: jupyter-malware
channels:
  - conda-forge
  - defaults
dependencies:
  # Python base
  - python=3.11
  - pip
  - ipykernel
  - ipywidgets
  
  # File Analysis
  - python-magic
  - pycryptodome
  - pyelftools
  
  # Data Processing
  - pandas
  - numpy
  - matplotlib
  
  # Networking
  - requests
  - dnspython
  - pyopenssl
  
  # Utilities
  - click
  - tqdm
  - colorama
  - tabulate
  
  # Database
  - sqlalchemy
  - redis-py
  
  # Pip packages for malware analysis
  - pip:
    # PE/ELF/Mach-O Analysis
    - pefile
    - lief
    - capstone
    - unicorn
    - keystone-engine
    
    # Document Analysis
    - oletools
    - python-docx
    - pdfplumber
    - pypdf2
    
    # Android Analysis
    - androguard
    - apkutils
    
    # Sandbox/Emulation
    - speakeasy-emulator
    - qiling
    
    # Yara
    - yara-python
    - yaramod
    
    # Disassembly
    - r2pipe
    - pwntools
    
    # Hashing/Crypto
    - ssdeep
    - tlsh
    - pymisp
    
    # Visualization
    - graphviz
    - networkx